### ISSUE TITLE
Complete R.array.country_list string array

### ISSUE THREAD

**Issue by snufflesrea** [snufflesrea/MyClock#9]
I made alert dialog which contain list of country timezone ID and user will select from this list, the selection will become input to set clock timezone.

Right now I am only putting one string inside the array resources. Need help to populate all country Java TimeZone ids and put it on R.array.country_list.

The Java TimeZone ids reference are [here](https://garygregory.wordpress.com/2013/06/18/what-are-the-java-timezone-ids/)

**Comment by mstieranka** [comment]
Hi, I looked into this and found out that there are 582 available TimeZone IDs in API 21, but 593 of them in API 28. In an array, some listed timezones will not be available on certain API levels. I think using `java.util.TimeZone.getAvailableIDs()` would be better, since it will return a list of timezones which will definitely work on the tested device.

**Comment by snufflesrea** [comment]
Alright. Let me try it tonight
